spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.40.132/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
#logging:
#  pattern:
    # 配置日志输出格式
#    console: "%d - %msg%n"
  # 配置日志文件路径  项目文件夹盘符根目录下logs文件夹
  # path: /logs
#  file: /log/sell.log
  # 配置日志级别
#  level:
#    com.lqy.sell.LoggerTest: debug
